services:
  db:
    image: postgres:17-alpine
    container_name: agile-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agile-store
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: agile-store
    container_name: agile-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/agile-store
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DDL_AUTO: update
    depends_on:
      - db
networks:
  postgres-compose-network:
    driver: bridge
