services:
  db:
    image: postgres:17-alpine
    container_name: agile-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agile-store
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  app:
    image: agile-store
    container_name: agile-app
    ports:
      - "8080:8080"
    depends_on:
      - db

